Repository CoolBitX-Technology/coolwallet-sdk, pull requests merged in 2025-04, with the labels that each got.

#980 🐛 [CW-24095] chore: sync master into beta on 2025-04-23 (fix - ARB USDT0 is not official token)
  packages/coin-evm/package-lock.json
  packages/coin-evm/package.json
  packages/coin-evm/src/chain/arbitrum/token.ts
  packages/coin-evm/tools/token.ts
Labels: Manual Review Time 5-10 min

#982 feat(nfc-transport): add APDU request and response logs
  packages/transport-react-native-nfc/package-lock.json
  packages/transport-react-native-nfc/package.json
  packages/transport-react-native-nfc/src/transport.ts
Labels: Manual Review Time 5-10 min

#981 fix: [CW-22271] add updateSEPart1 and updateSEPart2 to resolve iOS upgrade issue & update Go loadScript to v11
  packages/core/package-lock.json
  packages/core/package.json
  packages/core/src/apdu/execute/execute.ts
  packages/core/src/apdu/ota/index.ts
  packages/core/src/apdu/ota/ota.ts
  packages/core/src/apdu/script/go/otaScript.ts
Labels: Manual Review Time 10-20 min

#983 chore: CW-24146 do backup register data event if card is not recognized
  packages/core/src/apdu/ota/ota.ts
Labels: Manual Review Time 5-10 min

#986 feat(core): CW-24146 upgrade core to 2.0.0-beta.24 to fix ota flow
  packages/core/package-lock.json
  packages/core/package.json
  packages/core/tests/index.spec.ts
Labels: Manual Review Time 20-30 min
