Repository CoolBitX-Technology/coolwallet-sdk, pull requests merged in 2025-03, with the labels that each got.

#965 feat(aptos): support apto on go
  packages/coin-aptos/package-lock.json
  packages/coin-aptos/package.json
  packages/coin-aptos/src/config/types.ts
  packages/coin-aptos/src/index.ts
  packages/coin-aptos/src/utils/index.ts
  packages/coin-aptos/tests/index.spec.ts
Labels: Manual Review Time 1+ hours

#962 feat(zen): CW-21633 update zencash version to 2.0.0
  packages/coin-zen/package-lock.json
  packages/coin-zen/package.json
  packages/coin-zen/src/index.ts
  packages/coin-zen/src/sign.ts
  packages/coin-zen/src/utils/scriptUtil.ts
  packages/coin-zen/src/utils/transactionUtil.ts
  packages/coin-zen/tests/index.spec.ts
Labels: Manual Review Time 30-60 min

#967 chore(ada): support new tx type on go
  packages/coin-ada/package-lock.json
  packages/coin-ada/package.json
Labels: Manual Review Time 5-10 min

#968 feat(CRO): CW-21638 update cronos to v2
  packages/coin-cro/package-lock.json
  packages/coin-cro/package.json
  packages/coin-cro/src/config/params.ts
  packages/coin-cro/src/config/types.ts
  packages/coin-cro/src/sign.ts
  packages/coin-cro/src/utils/transactionUtils.ts
  packages/coin-cro/tests/index.spec.ts
Labels: Manual Review Time 10-20 min

#969 feat(cro): update tsconfig
  packages/coin-cro/tsconfig.json
Labels: Manual Review Time 5-10 min

#970 feat(zen): export script type from zen
  packages/coin-zen/package-lock.json
  packages/coin-zen/package.json
  packages/coin-zen/src/index.ts
Labels: Manual Review Time 5-10 min

#972 feat(Crypto.org): remove getSignedHex
  packages/coin-cro/package-lock.json
  packages/coin-cro/package.json
  packages/coin-cro/src/sign.ts
Labels: Manual Review Time 5-10 min

#971 feat(ICX): CW-23718 update to fit core v2.0
  packages/coin-icx/package-lock.json
  packages/coin-icx/package.json
  packages/coin-icx/src/config/params.ts
  packages/coin-icx/src/sign.ts
  packages/coin-icx/src/utils/scriptUtil.ts
  packages/coin-icx/src/utils/stringUtil.ts
  packages/coin-icx/src/utils/transactionUtil.ts
Labels: Manual Review Time 5-10 min

#922 ✨ feat: using new OTA service for Go
  packages/core/package-lock.json
  packages/core/package.json
  packages/core/src/apdu/ota/constants.ts
  packages/core/src/apdu/ota/ota.ts
  packages/core/src/apdu/script/go/otaScript.ts
Labels: Manual Review Time 10-20 min
