Repository CoolBitX-Technology/coolwallet-sdk, pull requests merged in 2025-02, with the labels that each got.

#955 ✨ [CW-21834] feat(ada): support cardano on coolwallet go
  packages/coin-ada/package-lock.json
  packages/coin-ada/package.json
  packages/coin-ada/src/index.ts
Labels: Manual Review Time 5-10 min

#957 fix(sol): 修正測試不過的問題 - [CW-23595]
  packages/coin-sol/jest.config.ts
  packages/coin-sol/package-lock.json
  packages/coin-sol/package.json
  packages/coin-sol/tests/index.spec.ts
Labels: Manual Review Time 1+ hours

#961 [CW-23648] feat: support ETC on go
  packages/coin-etc/package-lock.json
  packages/coin-etc/package.json
  packages/coin-etc/src/index.ts
  packages/coin-etc/tests/index.spec.ts
  packages/coin-etc/tsconfig.json
Labels: Manual Review Time 5-10 min

#958 [CW-23611] feat: support atom on go
  packages/coin-atom/.babelrc
  packages/coin-atom/package-lock.json
  packages/coin-atom/package.json
  packages/coin-atom/src/config/params.ts
  packages/coin-atom/src/index.ts
  packages/coin-atom/src/sign.ts
  packages/coin-atom/src/util/scriptUtil.ts
  packages/coin-atom/src/util/transactionUtil.ts
  packages/coin-atom/tests/teansactionUtil.test.ts
  packages/coin-atom/tests/transactionUtil.test.ts
  packages/coin-atom/tests/txProtobuf.test.ts
Labels: Manual Review Time 30-60 min
